### ISSUE TITLE
Preprocessed dataset not found when downloading from HF

### ISSUE THREAD

**Issue by willxxy** [sled-group/RACER#3]
Hello, thank you for the great work. 

When I execute the following command to download the preprocessed dataset from huggingface:

`dataset = load_dataset('sled-umich/RACER-replay-public', cache_dir='./.datasets')`

I get the following error

```
Traceback (most recent call last):
  File "get_datasets.py", line 5, in <module>
    dataset = load_dataset('sled-umich/RACER-replay-public', cache_dir='./.datasets')
  File "/home/william/anaconda3/envs/racer/lib/python3.8/site-packages/datasets/load.py", line 2132, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/william/anaconda3/envs/racer/lib/python3.8/site-packages/datasets/load.py", line 1853, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/william/anaconda3/envs/racer/lib/python3.8/site-packages/datasets/load.py", line 1717, in dataset_module_factory
    raise e1 from None
  File "/home/william/anaconda3/envs/racer/lib/python3.8/site-packages/datasets/load.py", line 1686, in dataset_module_factory
    return HubDatasetModuleFactoryWithoutScript(
  File "/home/william/anaconda3/envs/racer/lib/python3.8/site-packages/datasets/load.py", line 1071, in get_module
    module_name, default_builder_kwargs = infer_module_for_data_files(
  File "/home/william/anaconda3/envs/racer/lib/python3.8/site-packages/datasets/load.py", line 601, in infer_module_for_data_files
    raise DataFilesNotFoundError("No (supported) data files found" + (f" in {path}" if path else ""))
datasets.exceptions.DataFilesNotFoundError: No (supported) data files found in sled-umich/RACER-replay-public
```

The version to datasets==3.0.2.

**Comment by YinpeiDai** [comment]
Hi, our dataset is not complied with the `datasets` package. We recommend to download it by using `git clone git@hf.co:datasets/sled-umich/RACER-replay-public`  directly.

**Comment by willxxy** [comment]
Ok thank you!
